### ISSUE TITLE
Support r=<reviewer> style command

### ISSUE THREAD

**Issue by saneyuki** [nekoya/popuko#22]
I'd like to use `@<botname> r=<reviewer>`

**Comment by nekoya** [comment]
What is `r=<reviewer>` ideal behavior?

Now Popuko works

1. set status label `review`
2. merge the PR

Actions I'm considering are below.

1. change status label awaiting `review` to `merge`
2. merge the PR
3. set assignee(s)
4. delete branch

How about you?

**Comment by saneyuki** [comment]
At now, I think this should be just an alias.

**Comment by nekoya** [comment]
Okay, I got understanding `r=` means Okimochi.

**Comment by nekoya** [comment]
Is this issue completed?

**Comment by saneyuki** [comment]
Fixed by https://github.com/nekoya/popuko/pull/24
